//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MemDue
    {
        public int ID { get; set; }
        [Required]
        public string MemID { get; set; }
        [Required]
        public Nullable<double> PendingAmount { get; set; }
        [Required]
        public string Period { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> LastDate { get; set; }
        [Required]
        public Nullable<double> LastAmountPaid { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
