//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentorPremiseDetail
    {
        public int ID { get; set; }
        public string RentorID { get; set; }
        public string PremiseID { get; set; }
    
        public virtual Premis Premis { get; set; }
        public virtual Rentor Rentor { get; set; }
    }
}
