//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentorDue
    {
        public int ID { get; set; }
        public string RentID { get; set; }
        public Nullable<double> PendingAmount { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<double> LastAmountPaid { get; set; }
    
        public virtual Rentor Rentor { get; set; }
    }
}
