//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocietyEntities : DbContext
    {
        public SocietyEntities()
            : base("name=SocietyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<MemberPremiseDetail> MemberPremiseDetails { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemDue> MemDues { get; set; }
        public virtual DbSet<Premis> Premises { get; set; }
        public virtual DbSet<Rentor> Rentors { get; set; }
        public virtual DbSet<RentorDue> RentorDues { get; set; }
        public virtual DbSet<RentorPremiseDetail> RentorPremiseDetails { get; set; }
    }
}
